name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.**'
      - 'README.md'
      - 'LICENSE'
jobs:
  validate-mappings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install yamale
      run: |
        python -m pip install --upgrade pip
        pip install yamale
    - name: Download schema
      run: wget -O schema.yaml https://raw.githubusercontent.com/RickDB/PlexAniSync/master/custom_mappings_schema.yaml
    - name: Validate mappings
      run: yamale